# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Funding
    weight: 15
    url: '#funding'
  - name: Blog
    weight: 15
    url: '#blog'
  - name: Releases
    weight: 16
    url: 'https://oscar-project.github.io/documentation/versions/oscar-2301/'
  - name: FAQ
    weight: 17
    url: 'faq'
  - name: Publications
    url: '#featured'
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Team
    url: '#people'
    weight: 40
  - name: License
    url: '#license'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 50
  - name: Community
    url: 'https://discord.com/invite/4JNg9FTar4'
    weight: 60

